server.port=8080
spring.application.name=API-GATEWAY

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Flight Service
spring.cloud.gateway.routes[1].id=flight-service
spring.cloud.gateway.routes[1].uri=lb://FLIGHT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/flights/**

# Search Service
spring.cloud.gateway.routes[2].id=search-service
spring.cloud.gateway.routes[2].uri=lb://SEARCH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/search/**

# Booking Service
spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bookings/**

# Fare Service
spring.cloud.gateway.routes[4].id=fare-service
spring.cloud.gateway.routes[4].uri=lb://FARE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/fares/**

# Seat Service
spring.cloud.gateway.routes[5].id=seat-service
spring.cloud.gateway.routes[5].uri=lb://SEAT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/seats/**

# Payment Service
spring.cloud.gateway.routes[6].id=payment-service
spring.cloud.gateway.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/payments/**

# Invoice Service
spring.cloud.gateway.routes[7].id=invoice-service
spring.cloud.gateway.routes[7].uri=lb://INVOICE-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/invoices/**

# Notification Service
spring.cloud.gateway.routes[8].id=notification-service
spring.cloud.gateway.routes[8].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notifications/**

# Checkin Service
spring.cloud.gateway.routes[9].id=checkin-service
spring.cloud.gateway.routes[9].uri=lb://CHECKIN-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/checkins/**

# Flight Tracking Service
spring.cloud.gateway.routes[10].id=flight-tracking-service
spring.cloud.gateway.routes[10].uri=lb://FLIGHT-TRACKING-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/tracking/**

# Profile Service
spring.cloud.gateway.routes[11].id=profile-service
spring.cloud.gateway.routes[11].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/profiles/**

# JWT Configuration
jwt.secret=9a61f56cbd29fed7bcb6128a6f4ad5b5d4e6d6e7528d7070d76f66bda4e9f000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
