# ==========================================
# APPLICATION
# ==========================================

spring.application.name=payment-service


# ==========================================
# SERVER
# ==========================================

server.port=8084


# ==========================================
# MYSQL DATABASE
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=@Bluemoon257

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true




# ==========================================
# RABBITMQ
# ==========================================

spring.rabbitmq.host=localhost

spring.rabbitmq.port=5672

spring.rabbitmq.username=guest

spring.rabbitmq.password=guest


# ==========================================
# RABBITMQ CONNECTION
# ==========================================

spring.rabbitmq.listener.simple.acknowledge-mode=auto


# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework.web=INFO

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.amqp=INFO



spring.config.import=optional:configserver:http://localhost:8888