# Shared configurations across microservices
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret=9a61f56cbd29fed7bcb6128a6f4ad5b5d4e6d6e7528d7070d76f66bda4e9f000
jwt.expiration=86400000
